# Generated by Django 4.2.3 on 2023-07-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('selected_columns', models.TextField()),
                ('access_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='APIEndpoint',
        ),
    ]
